# Generated by Django 2.2.5 on 2022-08-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='board_name',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.CharField(default='web', max_length=64),
        ),
    ]
