# Generated by Django 2.2.5 on 2022-08-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220818_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hits',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
